spring:
  datasource:
    url: jdbc:mysql://localhost:8889/backend_ninja?useSSL=false
    username: ninja
    password: ninja
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect